import { useQuery } from '@tanstack/react-query'
import { Alert, Col, Row, Space } from 'antd'
import { monitorApi } from '../../api/monitorApi'
import { HandoffHealthPanel } from '../../components/monitor/HandoffHealthPanel'
import { MemoryHealthPanel } from '../../components/monitor/MemoryHealthPanel'
import { MessageBusHealthPanel } from '../../components/monitor/MessageBusHealthPanel'
import { MonitorAlertTable } from '../../components/monitor/MonitorAlertTable'
import { MonitorHistoryChart } from '../../components/monitor/MonitorHistoryChart'
import { MonitorMetricTable } from '../../components/monitor/MonitorMetricTable'
import { ReactHealthPanel } from '../../components/monitor/ReactHealthPanel'
import { ReflectionHealthPanel } from '../../components/monitor/ReflectionHealthPanel'
import { EmptyState } from '../../components/common/EmptyState'
import { PageHeader } from '../../components/common/PageHeader'
import { PageLoading } from '../../components/common/PageLoading'
import { ReadOnlyNotice } from '../../components/common/ReadOnlyNotice'
export function SystemMonitorPage(){ const summary=useQuery({queryKey:['web','monitor','summary'],queryFn:()=>monitorApi.summary()}); const services=useQuery({queryKey:['web','monitor','services'],queryFn:()=>monitorApi.services()}); const history=useQuery({queryKey:['web','monitor','history'],queryFn:()=>monitorApi.history()}); const alerts=useQuery({queryKey:['web','monitor','alerts'],queryFn:()=>monitorApi.alerts()}); if(summary.isLoading||services.isLoading)return <PageLoading/>; if(summary.error)return <EmptyState title="系统监控加载失败" description={String(summary.error)}/>; const service=services.data??{}; return <Space direction="vertical" size="large" style={{width:'100%'}}><PageHeader title="系统监控" description="生成不落库的当前快照，并读取已有历史和告警。"/><ReadOnlyNotice/><Alert type="info" showIcon message="当前快照不会保存" description="保存监控快照属于写操作，阶段 6.3 才接入。"/><MonitorMetricTable snapshot={summary.data?.snapshot??{}}/><Row gutter={[16,16]}><Col xs={24} md={12} xl={8}><MessageBusHealthPanel data={service.message_bus}/></Col><Col xs={24} md={12} xl={8}><MemoryHealthPanel data={service.memory}/></Col><Col xs={24} md={12} xl={8}><ReactHealthPanel data={service.react}/></Col><Col xs={24} md={12} xl={8}><ReflectionHealthPanel data={service.reflection}/></Col><Col xs={24} md={12} xl={8}><HandoffHealthPanel data={service.handoff}/></Col></Row><MonitorAlertTable alerts={summary.data?.alerts??alerts.data?.records??[]}/><MonitorHistoryChart records={history.data?.records??[]}/></Space> }
