ALTER TABLE user_profile ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE paper_order ADD COLUMN job_id TEXT;
ALTER TABLE paper_order ADD COLUMN run_id TEXT;
ALTER TABLE paper_order ADD COLUMN execution_source TEXT;
ALTER TABLE paper_decision_log ADD COLUMN job_id TEXT;
ALTER TABLE paper_decision_log ADD COLUMN run_id TEXT;
ALTER TABLE paper_decision_log ADD COLUMN execution_source TEXT;
ALTER TABLE agent_decision_log ADD COLUMN job_id TEXT;
ALTER TABLE agent_decision_log ADD COLUMN run_id TEXT;
ALTER TABLE agent_decision_log ADD COLUMN execution_source TEXT;
