from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from database.repositories import RecommendationRepository
from scoring.schemas import COMPLIANCE_DISCLAIMER


def _stock_code(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return text.split(".")[0].zfill(6)


def _parse_jsonish(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    text = value.strip()
    if not text or text[0] not in "[{":
        return value
    try:
        return json.loads(text)
    except Exception:
        return value


def _load_records(
    user_id: str = "default",
    db_path: str | Path | None = None,
) -> tuple[list[dict[str, Any]], str, str]:
    rows = RecommendationRepository(db_path).list_latest(user_id)
    records = [
        {key: _parse_jsonish(value) for key, value in row.items()}
        for row in rows
    ]
    return (
        records,
        "database/portfolio_recommendation_result",
        "read database" if records else "latest recommendation rows not found",
    )


def get_latest_recommendations(
    output_dir: str | Path = "outputs",
    top_k: int | None = None,
    risk_level: str | None = None,
    user_id: str = "default",
    db_path: str | Path | None = None,
) -> dict[str, Any]:
    del output_dir
    records, path, message = _load_records(user_id, db_path)
    filtered = list(records)
    if risk_level and risk_level != "all":
        filtered = [
            row
            for row in filtered
            if str(row.get("risk_level") or row.get("confidence") or "").lower()
            == str(risk_level).lower()
        ]
    if top_k is not None:
        filtered = filtered[: int(top_k)]
    adjustment_counts = Counter()
    for row in records:
        try:
            value = float(row.get("combined_adjustment") or 0.0)
        except Exception:
            value = 0.0
        if value > 0:
            adjustment_counts["positive"] += 1
        elif value < 0:
            adjustment_counts["negative"] += 1
        else:
            adjustment_counts["neutral"] += 1
    return {
        "ok": bool(records),
        "message": message,
        "path": path,
        "records": filtered,
        "total_count": len(records),
        "display_count": len(filtered),
        "adjustment_counts": dict(adjustment_counts),
        "compliance_disclaimer": COMPLIANCE_DISCLAIMER,
        "note": "numeric adjustments are scoring outputs, not real trading instructions.",
    }


def get_recommendation_by_stock(
    stock_code: str,
    output_dir: str | Path = "outputs",
    user_id: str = "default",
    db_path: str | Path | None = None,
) -> dict[str, Any]:
    target = _stock_code(stock_code)
    latest = get_latest_recommendations(
        output_dir=output_dir,
        user_id=user_id,
        db_path=db_path,
    )
    for row in latest.get("records", []):
        code = _stock_code(row.get("stock_code") or row.get("code"))
        if code == target:
            return {
                "ok": True,
                "record": row,
                "path": latest.get("path", ""),
                "compliance_disclaimer": COMPLIANCE_DISCLAIMER,
                "note": "This is not investment advice or a real trading instruction.",
            }
    return {
        "ok": False,
        "record": {},
        "message": f"no recommendation found for stock_code={target}",
        "path": latest.get("path", ""),
        "compliance_disclaimer": COMPLIANCE_DISCLAIMER,
    }


def explain_recommendation_fields() -> dict[str, Any]:
    return {
        "fields": {
            "original_pred_score": "Raw model score before user, news, and risk adjustments.",
            "original_pred_rank": "Raw model ranking before signal fusion.",
            "news_adjustment": "Raw numeric adjustment from mapped news or event evidence.",
            "effective_news_adjustment": "News adjustment after ai_reliability_weight scaling.",
            "user_adjustment": "Deterministic numeric adjustment from suitability and user constraints.",
            "combined_adjustment": "effective_news_adjustment + user_adjustment.",
            "position_adjustment_ratio": "clip(1 + combined_adjustment, 0.0, 2.0).",
            "target_weight": "Paper-trading target weight generated by rules, not a broker order.",
            "confidence": "Reliability summary for this fused result.",
            "triggered_rules": "Agent or scoring rules triggered during fusion.",
            "evidence_chunk_ids": "Long-lived evidence chunk ids used by scoring or Agent review.",
        },
        "compliance_disclaimer": COMPLIANCE_DISCLAIMER,
        "note": "numeric adjustments are not real trading instructions; target_weight is paper-trading context only.",
    }
