from __future__ import annotations

from .model_candidate_schema import ModelCandidate


def seed_candidates() -> list[ModelCandidate]:
    """Curated seed list from web-verified model families and project priorities."""
    rows = [
        dict(
            candidate_id="chronos_bolt",
            model_name="Chronos / Chronos-Bolt",
            category="A",
            source_type="huggingface",
            source_url="https://huggingface.co/amazon/chronos-bolt-small",
            paper_url="https://arxiv.org/abs/2403.07815",
            github_url="https://github.com/amazon-science/chronos-forecasting",
            hf_url="https://huggingface.co/amazon/chronos-bolt-small",
            has_pretrained_weight=True,
            weight_url="https://huggingface.co/amazon/chronos-bolt-small",
            has_training_code=True,
            has_inference_code=True,
            data_format_required="univariate/multivariate time series windows",
            input_type="close/OHLCV windows",
            output_type="forecast distribution / quantiles",
            task_type="time_series_forecasting",
            license="Apache-2.0",
            dependency_risk="medium",
            windows_compatibility="medium",
            python_version_required=">=3.10",
            estimated_difficulty="medium",
            priority=10,
            notes="Foundation model with public Hugging Face weights; needs stock-window adapter and no data leakage.",
        ),
        dict(
            candidate_id="timesfm",
            model_name="TimesFM",
            category="A",
            source_type="github+huggingface",
            source_url="https://github.com/google-research/timesfm",
            paper_url="https://arxiv.org/abs/2310.10688",
            github_url="https://github.com/google-research/timesfm",
            hf_url="https://huggingface.co/google/timesfm-1.0-200m",
            has_pretrained_weight=True,
            weight_url="https://huggingface.co/google/timesfm-1.0-200m",
            has_training_code=False,
            has_inference_code=True,
            data_format_required="time series context windows",
            input_type="close/OHLCV-derived series",
            output_type="future value forecast",
            task_type="time_series_forecasting",
            license="Apache-2.0",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=11,
            notes="Public pretrained foundation model; evaluate inference adapter before local training.",
        ),
        dict(
            candidate_id="moment",
            model_name="MOMENT",
            category="A",
            source_type="github+huggingface",
            source_url="https://github.com/moment-timeseries-foundation-model/moment",
            paper_url="https://arxiv.org/abs/2402.03885",
            github_url="https://github.com/moment-timeseries-foundation-model/moment",
            hf_url="https://huggingface.co/AutonLab/MOMENT-1-large",
            has_pretrained_weight=True,
            weight_url="https://huggingface.co/AutonLab/MOMENT-1-large",
            has_training_code=True,
            has_inference_code=True,
            data_format_required="time series tensors",
            input_type="OHLCV/feature windows",
            output_type="forecast / representation",
            task_type="time_series_foundation_model",
            license="MIT",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=12,
            notes="Public weights and code; useful as representation or direct forecast baseline.",
        ),
        dict(
            candidate_id="moirai_unit2s",
            model_name="Moirai / Uni2TS",
            category="A",
            source_type="github+huggingface",
            source_url="https://github.com/SalesforceAIResearch/uni2ts",
            paper_url="https://arxiv.org/abs/2402.02592",
            github_url="https://github.com/SalesforceAIResearch/uni2ts",
            hf_url="https://huggingface.co/Salesforce/moirai-1.0-R-small",
            has_pretrained_weight=True,
            weight_url="https://huggingface.co/Salesforce/moirai-1.0-R-small",
            has_training_code=True,
            has_inference_code=True,
            data_format_required="GluonTS-style time series dataset",
            input_type="close/OHLCV windows",
            output_type="probabilistic forecast",
            task_type="time_series_forecasting",
            license="Apache-2.0",
            dependency_risk="high",
            windows_compatibility="medium",
            estimated_difficulty="high",
            priority=13,
            notes="Strong foundation model family; dependency stack needs isolated environment check.",
        ),
        dict(
            candidate_id="lag_llama",
            model_name="Lag-Llama",
            category="A",
            source_type="github+huggingface",
            source_url="https://github.com/time-series-foundation-models/lag-llama",
            paper_url="https://arxiv.org/abs/2310.08278",
            github_url="https://github.com/time-series-foundation-models/lag-llama",
            hf_url="https://huggingface.co/time-series-foundation-models/Lag-Llama",
            has_pretrained_weight=True,
            weight_url="https://huggingface.co/time-series-foundation-models/Lag-Llama",
            has_training_code=True,
            has_inference_code=True,
            data_format_required="GluonTS-style time series dataset",
            input_type="close/OHLCV windows",
            output_type="probabilistic forecast",
            task_type="time_series_forecasting",
            license="Apache-2.0",
            dependency_risk="high",
            windows_compatibility="medium",
            estimated_difficulty="high",
            priority=14,
            notes="Public checkpoint; useful for foundation-model baseline after GluonTS adapter.",
        ),
        dict(
            candidate_id="patchtst",
            model_name="PatchTST",
            category="B",
            source_type="github",
            source_url="https://github.com/yuqinie98/PatchTST",
            paper_url="https://arxiv.org/abs/2211.14730",
            github_url="https://github.com/yuqinie98/PatchTST",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="long-format multivariate time series",
            input_type="OHLCV/Alpha158 windows",
            output_type="forecast horizon values",
            task_type="time_series_forecasting",
            license="MIT",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=20,
            notes="Good training candidate; no trusted public stock-specific weights found.",
        ),
        dict(
            candidate_id="time_series_library",
            model_name="Time-Series-Library",
            category="B",
            source_type="github",
            source_url="https://github.com/thuml/Time-Series-Library",
            paper_url="",
            github_url="https://github.com/thuml/Time-Series-Library",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="CSV time series benchmark format",
            input_type="OHLCV/feature windows",
            output_type="forecast or classification",
            task_type="time_series_forecasting",
            license="MIT",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=21,
            notes="Unified codebase for TimesNet, iTransformer, DLinear, NLinear, Autoformer, Informer, FEDformer.",
        ),
        dict(
            candidate_id="timesnet",
            model_name="TimesNet",
            category="B",
            source_type="github",
            source_url="https://github.com/thuml/TimesNet",
            paper_url="https://arxiv.org/abs/2210.02186",
            github_url="https://github.com/thuml/TimesNet",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="time series CSV",
            input_type="OHLCV/feature windows",
            output_type="forecast values",
            task_type="time_series_forecasting",
            license="MIT",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=22,
            notes="Train locally via original repo or Time-Series-Library wrapper.",
        ),
        dict(
            candidate_id="itransformer",
            model_name="iTransformer",
            category="B",
            source_type="github",
            source_url="https://github.com/thuml/iTransformer",
            paper_url="https://arxiv.org/abs/2310.06625",
            github_url="https://github.com/thuml/iTransformer",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="multivariate time series CSV",
            input_type="OHLCV/feature windows",
            output_type="forecast values",
            task_type="time_series_forecasting",
            license="MIT",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=23,
            notes="Promising local training candidate for cross-variable modeling.",
        ),
        dict(
            candidate_id="master_stock",
            model_name="MASTER",
            category="B",
            source_type="github",
            source_url="https://github.com/SJTU-DMTai/MASTER",
            paper_url="https://arxiv.org/abs/2312.15235",
            github_url="https://github.com/SJTU-DMTai/MASTER",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="Qlib stock features",
            input_type="Alpha158-like stock features",
            output_type="stock score",
            task_type="stock_prediction",
            license="unknown",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=25,
            notes="Finance-specific model; likely good local training candidate.",
        ),
        dict(
            candidate_id="stockmixer",
            model_name="StockMixer",
            category="B",
            source_type="github",
            source_url="https://github.com/SJTU-DMTai/StockMixer",
            paper_url="https://arxiv.org/abs/2401.10798",
            github_url="https://github.com/SJTU-DMTai/StockMixer",
            has_pretrained_weight=False,
            has_training_code=True,
            has_inference_code=True,
            data_format_required="stock feature tensors",
            input_type="OHLCV/Alpha158 stock panels",
            output_type="stock score",
            task_type="stock_prediction",
            license="unknown",
            dependency_risk="medium",
            windows_compatibility="medium",
            estimated_difficulty="medium",
            priority=26,
            notes="Stock-specific architecture; should train on current CSI300 split.",
        ),
        dict(
            candidate_id="dft_unet_external",
            model_name="DFT_UNET external checkpoint",
            category="A",
            source_type="local_checkpoint",
            source_url="D:/paper_work/Unet_DFT",
            has_pretrained_weight=True,
            weight_url="D:/paper_work/Unet_DFT/experiments/search_pure_unet_l3_seed0/DFT_UNET_dft_unet_l3_d64_ic_seed0_20260529_020115/best_model.pth",
            has_training_code=True,
            has_inference_code=True,
            data_format_required="[N, 8, 221] Alpha158 + market context",
            input_type="Alpha158 + 3-index market context",
            output_type="stock score",
            task_type="stock_prediction",
            license="local",
            dependency_risk="low",
            windows_compatibility="high",
            estimated_difficulty="low",
            priority=27,
            notes="Already adapted local checkpoint; keep as baseline in discovery table.",
        ),
    ]

    generic_models = [
        ("dlinear", "DLinear", "https://github.com/cure-lab/LTSF-Linear", "B", 31),
        ("nlinear", "NLinear", "https://github.com/cure-lab/LTSF-Linear", "B", 32),
        ("autoformer", "Autoformer", "https://github.com/thuml/Autoformer", "B", 33),
        ("informer", "Informer", "https://github.com/zhouhaoyi/Informer2020", "B", 34),
        ("fedformer", "FEDformer", "https://github.com/MAZiqing/FEDformer", "B", 35),
        ("crossformer", "Crossformer", "https://github.com/Thinklab-SJTU/Crossformer", "B", 36),
        ("scinet", "SCINet", "https://github.com/cure-lab/SCINet", "B", 37),
        ("tcn_baseline", "TCN baseline", "https://github.com/locuslab/TCN", "B", 40),
        ("lstm_gru_baseline", "LSTM/GRU baseline", "local_baseline", "B", 41),
        ("qlib_alstm", "Qlib ALSTM", "https://github.com/microsoft/qlib", "B", 45),
        ("qlib_sfm", "Qlib SFM", "https://github.com/microsoft/qlib", "B", 46),
        ("qlib_tra", "Qlib TRA", "https://github.com/microsoft/qlib", "B", 47),
        ("qlib_hist", "Qlib HIST", "https://github.com/microsoft/qlib", "B", 48),
        ("qlib_rsr", "Qlib RSR", "https://github.com/microsoft/qlib", "B", 49),
        ("graph_stock_gats", "GATs / graph stock models", "https://github.com/microsoft/qlib", "B", 50),
        ("lightgbm_alpha158", "LightGBM Alpha158 baseline", "local_baseline", "B", 55),
        ("timegpt", "TimeGPT", "https://www.nixtla.io/docs", "C", 80),
        ("timer", "Timer", "https://github.com/thuml/Large-Time-Series-Model", "B", 60),
        ("unitime", "UniTime", "https://github.com/liuxu77/UniTime", "B", 65),
    ]
    for candidate_id, name, url, category, priority in generic_models:
        rows.append(
            dict(
                candidate_id=candidate_id,
                model_name=name,
                category=category,
                source_type="github" if url.startswith("http") else "local",
                source_url=url,
                github_url=url if "github.com" in url else "",
                has_pretrained_weight=False,
                has_training_code=True,
                has_inference_code=True,
                data_format_required="model-specific time series or Qlib format",
                input_type="OHLCV/Alpha158 windows",
                output_type="forecast value or stock score",
                task_type="time_series_forecasting" if "qlib" not in candidate_id else "stock_prediction",
                license="unknown",
                dependency_risk="medium",
                windows_compatibility="unknown",
                estimated_difficulty="medium",
                priority=priority,
                notes="Seed candidate; needs repository inspection before download/training.",
            )
        )

    return [ModelCandidate(**row) for row in rows]
